Obrana: 1.4
Vitalita: 1.3
Síla: 1.1
Přesnost: 0.75
Potřebný Lvl: 0.0
Vyhýbání: 3.0
Poškození: 2.0
Inteligence: 1.1
Šance na kritický zásah: 1.5
Kritický útok: 1.1
Víra: 0.85
Regenerace many: 1.2
Síla léčebných kouzel: 2.0
